[client]
showErrorDetails = false
toolbarMode = "minimal"

[logger]
level = "error"

[server]
maxUploadSize = 200
enableXsrfProtection = false
headless = true

[theme]
primaryColor = "#1e88e5"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
